name: Build and test
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.png'
      - '**.editorconfig'
      - '**.csv'
      - '**codeql-analysis.yml'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.png'
      - '**.editorconfig'
      - '**.csv'
      - '**codeql-analysis.yml'
jobs:
  test:
    name: Test `${{ matrix.options.tf }}` on `${{ matrix.options.os }}`
    runs-on: ${{ matrix.options.os }}
    strategy:
      matrix:
        options:
          # net8.0
          - os: ubuntu-latest
            tf: net8.0
          - os: windows-latest
            tf: net8.0
          - os: macos-latest
            tf: net8.0
          # net7.0
          - os: ubuntu-latest
            tf: net7.0
          # net462
          - os: windows-latest
            tf: net462
    steps:
     - name: Checkout
       uses: actions/checkout@v2.5.0

     - name: Setup dotnet
       uses: actions/setup-dotnet@v3.0.3
       with:
         dotnet-version: ${{ matrix.options.rv }}

     - name: Publish tests
       run: dotnet publish "test/FirmaXadesNetCore.Tests/FirmaXadesNetCore.Tests.csproj" -o ".deploy/FirmaXadesNetCore.Tests" -c "Release" -f "${{ matrix.options.tf }}"

     - name: Run tests
       run: dotnet vstest ".deploy/FirmaXadesNetCore.Tests/FirmaXadesNetCore.Tests.dll" --ResultsDirectory:".deploy/FirmaXadesNetCore.Tests/TestResults"
